apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: elixir-sample-pipeline-node
  namespace: myproject
spec:
  nodeSelector: {}
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: hello_phx
    git:
      ref: stephen-wip-1
      uri: 'http://hlgithub.hobbylobby.corp/stmhall1/openshift-microservice.git'
    sourceSecret:
      name: svc-jenkins
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      env:
        - name: PS_GIT_URI
          value: 'http://hlgithub.hobbylobby.corp/stmhall1/openshift-microservice.git'
        - name: PS_GIT_REF
          value: stephen-wip-1
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline
  triggers: []